
CREATE VIEW [DWH].[VW_CARTEIRA] AS 
WITH [DATE] AS (
    SELECT C.Data AS DATA_REF
    FROM DWH.[DATE]ENDARIO AS C
    WHERE C.Data = EOMONTH(C.Data)        
      AND MONTH(C.Data) IN (3,6,9,12)     
)
SELECT
     [DATE].DATA_REF
    ,CTT.[COD CONTRATO]
    ,CTT.[COD CLIENTE]
    ,CTT.[NATUREZA]
    ,CTT.[SEGMENTO]
    ,CTT.[SETOR ATIVIDADE]
    ,CTT.[UF]
    ,CTT.[REGIONAL]
    ,CTT.[COD PRODUTO]
    ,CTT.[DESC PRODUTO]
    ,CTT.[SISTEMA ARMOTIZACAO]
    ,CTT.[GARANTIA]
    ,CTT.[RISCO DE GARANTIA]
	,CTT.[STATUS CONTRATO]

	,SUM(
		CASE 
			WHEN PCL.[DATA VENCIMENTO] <= [DATE].DATA_REF THEN ISNULL(PCL.[VALOR PRINCIPAL],0)
			ELSE 0
		END) AS [VALOR PARCELA]

	,SUM(
		CASE
			WHEN PCL.[DATA PAGAMENTO] IS NOT NULL
             AND PCL.[DATA PAGAMENTO] <= [DATE].DATA_REF
		THEN ISNULL(PCL.[VALOR PAGO],0)
            ELSE 0
		END) AS [VALOR PAGO]

    ,SUM(CASE
            WHEN PCL.[DATA PAGAMENTO] IS NOT NULL
             AND PCL.[DATA PAGAMENTO] <= [DATE].DATA_REF
         THEN CASE
            WHEN ISNULL(PCL.[VALOR PRINCIPAL],0) - ISNULL(PCL.[VALOR PAGO],0) > 0
         THEN ISNULL(PCL.[VALOR PRINCIPAL],0) - ISNULL(PCL.[VALOR PAGO],0)
            ELSE 0
         END
            ELSE ISNULL(PCL.[VALOR PRINCIPAL],0)
         END) AS [VALOR A PAGAR]

    ,SUM(CASE
            WHEN PCL.[DATA VENCIMENTO] > [DATE].DATA_REF
         THEN
         CASE
            WHEN PCL.[DATA PAGAMENTO] IS NOT NULL
             AND PCL.[DATA PAGAMENTO] <= [DATE].DATA_REF
         THEN CASE
            WHEN ISNULL(PCL.[VALOR PRINCIPAL],0) - ISNULL(PCL.[VALOR PAGO],0) > 0
         THEN ISNULL(PCL.[VALOR PRINCIPAL],0) - ISNULL(PCL.[VALOR PAGO],0)
            ELSE 0
         END
            ELSE ISNULL(PCL.[VALOR PRINCIPAL],0)
         END
            ELSE 0
         END) AS [SALDO A VENCER],

 
    SUM(
		CASE
            WHEN PCL.[DATA VENCIMENTO] <= [DATE].DATA_REF
        THEN
        CASE
            WHEN PCL.[DATA PAGAMENTO] IS NOT NULL
             AND PCL.[DATA PAGAMENTO] <= [DATE].DATA_REF
        THEN 
		CASE
            WHEN ISNULL(PCL.[VALOR PRINCIPAL],0) - ISNULL(PCL.[VALOR PAGO],0) > 0
        THEN ISNULL(PCL.[VALOR PRINCIPAL],0) - ISNULL(PCL.[VALOR PAGO],0)
            ELSE 0
        END
            ELSE ISNULL(PCL.[VALOR PRINCIPAL],0)
        END
            ELSE 0
        END) AS [SALDO VENCIDO],


	MAX(
		CASE
			WHEN PCL.[DATA VENCIMENTO] <= [DATE].DATA_REF
            AND (PCL.[DATA PAGAMENTO] IS NULL OR PCL.[DATA PAGAMENTO] > [DATE].DATA_REF)
        THEN DATEDIFF(DAY, PCL.[DATA VENCIMENTO],
        CASE 
            WHEN [DATE].DATA_REF <= dbo.ufn_DataRef() THEN [DATE].DATA_REF
            ELSE dbo.ufn_DataRef()
        END)
			ELSE 0
		END) AS [DIAS ATRASO],


	ISNULL(
		MAX(
			CASE
				WHEN PCL.[DATA VENCIMENTO] <= [DATE].DATA_REF
                AND (PCL.[DATA PAGAMENTO] IS NULL OR PCL.[DATA PAGAMENTO] > [DATE].DATA_REF)
            THEN
			CASE
                WHEN DATEDIFF(DAY, PCL.[DATA VENCIMENTO], [DATE].DATA_REF) <= 30 THEN '0-30'
                WHEN DATEDIFF(DAY, PCL.[DATA VENCIMENTO], [DATE].DATA_REF) <= 60 THEN '31-60'
                WHEN DATEDIFF(DAY, PCL.[DATA VENCIMENTO], [DATE].DATA_REF) <= 90 THEN '61-90'
                ELSE '91+'
                END
				ELSE NULL
        END),'S/A') AS [BUCKET ATRASO]


FROM [DATE]
LEFT JOIN DWH.VW_CONTRATOS CTT
    ON CTT.[DATA CONTRATACAO] <= [DATE].DATA_REF

LEFT JOIN DWH.VW_PARCELAS PCL
    ON PCL.[ID CONTRATO] = CTT.[COD CONTRATO]
   AND PCL.[ID CLIENTE]  = CTT.[COD CLIENTE]
   AND PCL.[ID PRODUTO]  = CTT.[COD PRODUTO]

WHERE 
[DATE].DATA_REF <= dbo.ufn_DataRef()

GROUP BY
    [DATE].DATA_REF,
    CTT.[COD CONTRATO],
    CTT.[COD CLIENTE],
    CTT.[NATUREZA],
    CTT.[SEGMENTO],
    CTT.[SETOR ATIVIDADE],
    CTT.[UF],
    CTT.[REGIONAL],
    CTT.[COD PRODUTO],
    CTT.[DESC PRODUTO],
    CTT.[SISTEMA ARMOTIZACAO],
    CTT.[GARANTIA],
    CTT.[RISCO DE GARANTIA],
	CTT.[STATUS CONTRATO],
	CTT.[STATUS CONTRATO] 
GO


