
CREATE VIEW [DWH].[CLIENTES] AS 
SELECT CLT.[TCL_ID_CLIENTE]         AS [ID CLIENTE]
      ,[TCL_TIPO_CLIENTE]           AS [TIPO CLIENTE]
      ,[TCL_NOME_RAZAO]             AS [RAZAO SOCIAL]
      ,[TCL_UF]                     AS [UF]
      ,[TCL_MUNICIPIO]              AS [MUNICIPIO]
      ,[TCL_CEP]                    AS [CEP]
      ,[TCL_SEGMENTO]               AS [SEGMENTO]
      ,UPPER([TCL_REGIAO])          AS [REGIONAL]
	  ,CASE WHEN [TCL_TIPO_CLIENTE] = 'PF' THEN 'PF' ELSE EMP.TEP_PORTE END AS [PORTE]
	  ,CASE WHEN [TCL_TIPO_CLIENTE] = 'PF' THEN 'PESSOAL' ELSE EMP.TEP_NATUREZA_JURIDICA END AS [NATUREZA]
  FROM [dbo].[CLIENTES] CLT
LEFT JOIN EMPRESAS EMP ON CLT.TCL_ID_CLIENTE = EMP.TCL_ID_CLIENTE


GO


