
CREATE VIEW [DWH].[VW_CONTRATOS] AS

WITH REF AS (
    SELECT EOMONTH(GETDATE()) AS DATA_REF   
),
ATR AS (
    SELECT
        P.FCT_ID_CONTRATO,
        MAX(
            CASE
                WHEN ISNULL(P.FPA_VL_PAGO,0) = 0 AND P.FPA_DT_VENCIMENTO <= R.DATA_REF
                    THEN DATEDIFF(DAY, P.FPA_DT_VENCIMENTO, R.DATA_REF)
                WHEN ISNULL(P.FPA_VL_PAGO,0 )> 0 AND P.FPA_DT_PAGAMENTO > P.FPA_DT_VENCIMENTO
                    THEN DATEDIFF(DAY, P.FPA_DT_VENCIMENTO, P.FPA_DT_PAGAMENTO)
                ELSE 0
            END
        ) AS MAX_DIAS_ATRASO
    FROM dbo.PARCELA_BASE P
    CROSS JOIN REF R
    GROUP BY P.FCT_ID_CONTRATO
)
SELECT
      FCT.FCT_ID_CONTRATO                    AS [COD CONTRATO]
    , FCT.TCL_ID_CLIENTE                     AS [COD CLIENTE]
    , DCL.TCL_NOME_RAZAO                     AS [NOME CLIENTE]
    , CASE WHEN DCL.TCL_TIPO_CLIENTE='PF' THEN 'PESSOA FISICA' ELSE 'PESSOA JURIDICA' END AS [NATUREZA]
    , UPPER(DCL.TCL_REGIAO)                  AS [REGIONAL]
    , DCL.TCL_UF                             AS [UF]
    , DCL.TCL_SEGMENTO                       AS [SEGMENTO]
    , DSE.TSE_NM_SETOR                       AS [SETOR ATIVIDADE]
    , FCT.FCT_CANAL_ORIGEM                   AS [CANAL CLIENTE]
    , FCT.DPC_ID_PROD                        AS [COD PRODUTO]
    , DPC.DPC_NOM_PROD                       AS [DESC PRODUTO]
    , DPC.DPC_SIST_AMORT                     AS [SISTEMA ARMOTIZACAO]
	, DGR.DGR_DESC                           AS [GARANTIA]
	, DGR.DGR_RISCO                          AS [RISCO DE GARANTIA]
    , FCT.FCT_CARENCIA_MESES                 AS [CARENCIA]
    , FCT.FCT_MOEDA                          AS [MOEDA CONTRATUAL]
    , CONVERT(DATE, FCT.FCT_DT_CONTRATACAO)  AS [DATA CONTRATACAO]
    , CONVERT(CHAR(7), FCT.FCT_DT_CONTRATACAO, 23) AS [VINTAGE]
    , CONVERT(DATE, DATEADD(MONTH, FCT.FCT_PRAZO_MESES, FCT.FCT_DT_CONTRATACAO)) AS [DATA VENCIMENTO CONTRATO]
    , FCT.FCT_PRAZO_MESES                    AS [PRAZO MESES]
    , FCT.FCT_DIA_VENCIMENTO                 AS [DIA VENCTO]
    , FCT.FCT_INDEXADOR                      AS [INDEXADOR]
    , POWER(1.0 + TRY_CONVERT(DECIMAL(18,8), FCT.FCT_TX_AA), 1.0/12.0) - 1.0 AS [TAXA MENSAL]
    , FCT.FCT_TX_AA                          AS [TAXA ANUAL]
    , FCT.FCT_VALOR_PRINCIPAL                AS [VALOR LIBERADO]
    , FCT.FCT_STATUS_OPERACIONAL             AS [STATUS CONTRATO]

    , CASE
        WHEN ISNULL(ATR.MAX_DIAS_ATRASO,0) <= 0  THEN 'SEM ATRASO'
        WHEN ATR.MAX_DIAS_ATRASO BETWEEN 1 AND 30   THEN '1 A 30 DIAS'
        WHEN ATR.MAX_DIAS_ATRASO BETWEEN 31 AND 60  THEN '31 A 60 DIAS'
        WHEN ATR.MAX_DIAS_ATRASO BETWEEN 61 AND 90  THEN '61 A 90 DIAS'
        WHEN ATR.MAX_DIAS_ATRASO BETWEEN 91 AND 180 THEN '91 A 180 DIAS'
        ELSE 'ACIMA DE 180 DIAS'
      END AS BUCKET_CONTRATO
    
	, CASE WHEN MAX_DIAS_ATRASO > 91 THEN 1 ELSE 0 END AS [INADIMPLENTE]

FROM dbo.CONTRATO_BASE FCT
LEFT JOIN ATR
       ON ATR.FCT_ID_CONTRATO = FCT.FCT_ID_CONTRATO
INNER JOIN dbo.CLIENTES DCL
        ON DCL.TCL_ID_CLIENTE = FCT.TCL_ID_CLIENTE
INNER JOIN dbo.PRODUTOS DPC
        ON DPC.DPC_ID_PROD = FCT.DPC_ID_PROD
LEFT  JOIN dbo.GARANTIAS DGR
        ON DGR.DGR_ID_GARANTIA = FCT.DGR_ID_GARANTIA 
LEFT  JOIN dbo.SETOR_ATIVIDADE DSE
        ON DSE.TSE_ID_SETOR = FCT.TSE_ID_SETOR

		
GO


