
CREATE VIEW [DWH].[VW_PARCELAS] AS 
SELECT
      FPA.FPA_ID_PARCELA                         AS [ID PARCELA]
     ,FPA.FCT_ID_CONTRATO                        AS [ID CONTRATO]
     ,FCT.TCL_ID_CLIENTE                         AS [ID CLIENTE]
     ,FPA.DPC_ID_PROD                            AS [ID PRODUTO]
	 ,FPA.FPA_MOEDA                              AS [MOEDA]
     ,FPA.FPA_CANAL_PAGAMENTO                    AS [CANAL]
     ,FPA.FPA_MEIO_PAGAMENTO                     AS [MEIO PAGAMENTO]
     ,CONVERT(DATE, FPA.FPA_DT_PAGAMENTO, 103)   AS [DATA PAGAMENTO]
     ,CONVERT(DATE, FPA.FPA_DT_VENCIMENTO, 103)  AS [DATA VENCIMENTO]
     ,FPA.FPA_NR_PARCELA                       AS [QTD PARCELA]
	 ,FPA.FPA_VL_PRINCIPAL + FPA_VL_JUROS + FPA_VL_ENCARGOS + FPA_MULTA_PAGA - FPA_DESCONTO_CONCEDIDO AS [VALOR PRINCIPAL]
     ,FPA.FPA_VL_PAGO                          AS [VALOR PAGO]
     ,CASE
         WHEN ISNULL(FPA.FPA_VL_PAGO,0) > 0
              AND CA.DIASATRASO > 0        
			THEN 'PAGA EM ATRASO'
         WHEN ISNULL(FPA.FPA_VL_PAGO,0) > 0 
			THEN 'PAGA'
         WHEN ISNULL(FPA.FPA_VL_PAGO,0) = 0
              AND dbo.ufn_DataRef() > FPA.FPA_DT_VENCIMENTO THEN 'EM ATRASO'
         WHEN ISNULL(FPA.FPA_VL_PAGO,0) = 0 THEN 'PENDENTE'
         ELSE 'INDEFINIDO'
       END                                   AS [STATUS PAGAMENTO]
	 
     ,CA.DIASATRASO                          AS [DIAS ATRASO]
     ,CASE
         WHEN CA.DIASATRASO <= 0               THEN 'Sem atraso'
         WHEN CA.DIASATRASO BETWEEN 1  AND 30  THEN '1 a 30'
         WHEN CA.DIASATRASO BETWEEN 31 AND 60  THEN '31 a 60'
         WHEN CA.DIASATRASO BETWEEN 61 AND 90  THEN '61 a 90'
         WHEN CA.DIASATRASO BETWEEN 91 AND 180 THEN '91 a 180'
         ELSE 'Acima 180 dias'
       END                                    AS [BUCKET]
	 
     , FPA.FPA_CANAL_PAGAMENTO                AS [CANAL PAGAMENTO]
     , CAST(NULL AS VARCHAR(50))              AS [ORIGEM BAIXA] 

FROM dbo.PARCELA_BASE AS FPA
CROSS APPLY (
    SELECT CASE
        WHEN ISNULL(FPA.FPA_VL_PAGO,0) > 0
             AND FPA.FPA_DT_PAGAMENTO IS NOT NULL
             AND FPA.FPA_DT_PAGAMENTO > FPA.FPA_DT_VENCIMENTO
            THEN DATEDIFF(DAY, FPA.FPA_DT_VENCIMENTO, FPA.FPA_DT_PAGAMENTO)

        WHEN ISNULL(FPA.FPA_VL_PAGO,0) = 0
             AND dbo.ufn_DataRef() > FPA.FPA_DT_VENCIMENTO
            THEN DATEDIFF(DAY, FPA.FPA_DT_VENCIMENTO, dbo.ufn_DataRef())

        ELSE 0
    END AS DIASATRASO
) CA
INNER JOIN dbo.CONTRATO_BASE AS FCT
        ON FCT.FCT_ID_CONTRATO = FPA.FCT_ID_CONTRATO
INNER JOIN dbo.CLIENTES AS DCL
        ON DCL.TCL_ID_CLIENTE = FCT.TCL_ID_CLIENTE



