
CREATE VIEW [DWH].[PRODUTO] AS
SELECT 
       DPC_ID_PROD       AS [ID PRODUTO]
      ,DPC_NOM_PROD      AS [PRODUTO]
	  ,CASE 
	       WHEN [DPC_ID_PROD] = '0001' THEN 'CONSIGNADO' 
		   WHEN [DPC_ID_PROD] = '0002' THEN 'MICROCREDITO'
		   WHEN [DPC_ID_PROD] = '0003' THEN 'CONSIGNADO'
		   WHEN [DPC_ID_PROD] = '0004' THEN 'VEICULAR'
		   WHEN [DPC_ID_PROD] = '0005' THEN 'MICROCREDITO'
		   WHEN [DPC_ID_PROD] = '0006' THEN 'IMOBILIARIO'
		   WHEN [DPC_ID_PROD] = '0007' THEN 'MICROCREDITO' 
		   WHEN [DPC_ID_PROD] = '0008' THEN 'IMOBILIARIO' ELSE 'OUTRO' END AS [PRODUTO REDUZ]
      ,DPC_TIPO_PROD     AS [TIPO PRODUTO]
      ,DPC_SIST_AMORT    AS [SISTEMA AMORTIZACAO]
      ,DPC_INDEXADOR     AS [INDEXADOR]
      ,DPC_PRAZO_MIN     AS [PRAZO MINIMO]
      ,DPC_PRAZO_MAX     AS [PRAZO MAXIMO]
      ,DPC_TX_MIN_AA     AS [TAXA MINIMA AA]
      ,DPC_TX_MAX_AA     AS [TAXA MAXIMA AA]
      ,DPC_CARENCIA      AS [CARENCIA]
      ,DPC_MOEDA         AS [MOEDA]
      ,DPC_ST_PROD       AS [STATUS]
      ,DPC_SRC_SYS       AS [SISTEMA ORIGEM]
      ,DPC_LOAD_TS       AS [DATA CARGA]
      ,DPC_RUN_ID        AS [RUN ID]
      ,DPC_VLD_FROM      AS [VALIDO DE]
      ,DPC_VLD_TO        AS [VALIDO ATE]
      ,DPC_IS_CURR       AS [REGISTRO ATUAL]
FROM dbo.PRODUTOS;
GO


